### ISSUE TITLE
how to see the codes?

### ISSUE THREAD

**Issue by Mayur-7** [GianC-Dev/NitroGen-V2#5]

**Comment by Mayur-7** [comment]
HOW TO SEE THE CODES?

**Comment by GianC-Dev** [comment]
![Uploading IMG_20201206_174852.jpg…]()

**Comment by GianC-Dev** [comment]
![IMG_20201206_174852](https://user-images.githubusercontent.com/52561965/101283440-69fd9200-37eb-11eb-9ee9-2f9feb6c40f3.jpg)
